server:
  port: 9000
spring:
  application:
    name: oauth-server
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver




logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE