server:
  port: 8099

spring:
  application:
    name: users-service
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

  datasource:
    url: "jdbc:mysql://localhost:3306/users_service?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true"
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
