server:
  port: 8765
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: resourceRoute
          uri: http://127.0.0.1:8787/
          predicates:
            - Path=/api/v1/resources/**
        # tp access angular, we have to access port 8765
        - id: angular
          uri: http://127.0.0.1:4200/
          predicates:
            - Path=/**

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8765/login/oauth2/code/gateway
          oidc-client:
            provider: spring
            client-id: oidc-client
            client-secret: secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8765/authorized

        provider:
          spring:
            issuer-uri: http://localhost:9000