server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users-status
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/status
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: usersRoutes
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: tokensRoutes
          uri: http://localhost:8081
          predicates:
            - Path=/api/tokens/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: albums-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/albums
        - id: photos-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/photos
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka